import type { Metadata } from "next";
import { Geist, Geist_Mono ,  Playfair_Display } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
// 1. Define the font object, specifying subsets and weights
const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'], // Match the weights (400 to 900)
  variable: '--font-playfair', // A CSS variable name to reference the font
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ROYAL",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white ${playfair.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
